#!/bin/sh

alias s="sketchybar"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
FONT="JetBrainsMono Nerd Font"
FONTALT="Helvetica"

. $PLUGIN_DIR/colors.sh

# Bar appearance

s --bar height=24        \
                 blur_radius=0   \
                 position=bottom  \
                 y_offset=3       \
                 margin=6         \
                 corner_radius=8  \
                 padding_left=10  \
                 padding_right=10 \
                 shadow=on        \
                 topmost=on        \
                 color=$BAR

# Defaults

s --default updates=when_shown                        \
                     drawing=on                                \
                     icon.font="$FONT:Bold:18.0"               \
                     icon.color=$FOREGROUND                     \
                     label.font="$FONT:Bold:16.0"              \
                     label.color=$FOREGROUND                    \
                     label.padding_left=4                      \
                     label.padding_right=4                     \
                     icon.padding_left=6                       \
                     icon.padding_right=6

# Left items

s --add  item  hide  left                                 \
           --set  hide        click_script="$PLUGIN_DIR/hide.sh"    \
                              icon.drawing=off                      \
                              label.drawing=on                      \
                              label="❚"

s --add item yabai_mode left \
              --set yabai_mode update_freq=3 \
                            script="$PLUGIN_DIR/yabai_mode.sh" \
                            label.drawing=off               \
                        --subscribe yabai_mode space_change



# Center items

SPACE_ICONS=("" "爵" "" "" "" "" "" "8" "9" "10")
# SPACE_ICONS=("float" "web" "work" "code" "org" "term" "7" "8" "9" "10")
for i in "${!SPACE_ICONS[@]}"
do
  sid=$(($i+1))
  s --add space space.$sid center                                 \
             --set space.$sid associated_space=$sid                      \
                              icon=${SPACE_ICONS[i]}                     \
                              icon.highlight_color=$RED                  \
                              label.drawing=off                          \
                              background.drawing=on                          \
                              click_script="yabai -m space --focus $sid"
done

# Right items

s --add item clock right                        \
           --set clock   update_freq=30                  \
                         icon.drawing=off                 \
                        icon.padding_left=0 \
                         label.font="$FONT:ExtraBold:14.0"          \
                         label.align=center \
                         label.color=$FOREGROUND \
                         script="$PLUGIN_DIR/clock.sh"              \
           --subscribe                 clock system_woke             

s --add item battery right \
              --set battery update_freq=3 \
                            script="$PLUGIN_DIR/power.sh" \
                            icon.padding_left=10                   \
                            icon=                   \
                            label.drawing=off
                            

sketchybar --add slider volume right 50                                           \
           --set volume script="sketchybar --set volume slider.percentage=\$INFO" \
                        slider.highlight_color=0xff8aadf4                         \
                        slider.background.height=10                               \
                        slider.background.corner_radius=3                         \
                        slider.background.color=0xff494d64                        \
                        icon.drawing=off                                         \
                        label.drawing=off                                         \
           --subscribe volume volume_change

s --add item sound right \
              --set sound update_freq=3 \
                            script="$PLUGIN_DIR/sound.sh" \
                            icon=墳                   \
                            icon.align=left                   \
                            icon.padding_right=10                   \
                            label.drawing=off              \
                         --subscribe sound volume_change


s --add item wifi right \
              --set wifi update_freq=3 \
                            script="$PLUGIN_DIR/wifi.sh" \
                            icon=睊                   \
                            label.drawing=off

# Finalize

s --update

echo "s configuration loaded.."
